### PR TITLE
♻️ Refactor and complete sharing feature

### PR DESCRIPTION
**Pull request by Kyziq**
**Improvise #90
Related #16, #32** 

From what I research, tak directly possible to embed the QR code image into the message using intent URL dekat X dengan WhatsApp. The closest yang boleh is sending the URL link in the message, and contoh nanti dekat X, akan show the banner, X card (a feature that has been implemented)

Unless kalau nak embed QR jugak, kena upload QR image ke server, and maybe involve Twitter Developer Platform? [twitter-api-v2](https://www.npmjs.com/package/twitter-api-v2)?

But I think the current way here should be enough

**Demo using mobile** (URL will work fine bila dah deploy huhu)

https://github.com/user-attachments/assets/b6a12c95-bc1c-46e5-ba0b-e5fc7cf9a57d

**Preview**

image

**Changes**
- Introduce generic `Share` component with multi-platform support
- Add platform icons usage
- Enable app opening based on device detection
- Add fallback mechanisms (kalau nak buka app tak boleh, open app in the current browser)
- Improve message content
- Remove unused `ID` field

**References**
[StackOverflow 1](https://stackoverflow.com/questions/71022441/can-i-send-a-image-to-whatsapp-using-html-hyperlink-a-tag), [StackOverflow 2](https://stackoverflow.com/questions/39435020/how-to-share-image-and-text-on-whatsapp-using-javascript), [X Cards](https://developer.x.com/en/docs/x-for-websites/cards/overview/abouts-cards), [X Web Intents](https://developer.x.com/en/docs/x-for-websites/web-intents/overview), [X URL schemes for the iOS and Android apps](https://github.com/takumi3y/URLScheme/wiki/Twitter)

### CODE REVIEW

**Comment by khrnchn** [comment]
kemantapan 🚀

**Comment by Kyziq** [comment]
@khrnchn Ok kee mesej tu hshshs

image

**Comment by khrnchn** [comment]
> @khrnchn Ok kee mesej tu hshshs
> 
> 
> 
> image
> 
> 

ok je, ataupun link dulu then terima kasih tu. btw possible ke dynamic og image using qr tu?

**Comment by Kyziq** [comment]
> ok je, ataupun link dulu then terima kasih tu.

Nak tukar?

>  btw possible ke dynamic og image using qr tu?

Untuk attach QR ke message atau post eh?

**Comment by khrnchn** [comment]
> > ok je, ataupun link dulu then terima kasih tu.
> 
> 
> 
> Nanti tolong tukarkan kalau nak update hehe
> 
> 
> 
> >  btw possible ke dynamic og image using qr tu?
> 
> 
> 
> Untuk attach QR ke message atau post eh?

haah either attach gambar qr terus, atau dynamically render as og image

**Comment by imanazri** [comment]
dynamically render OG image tu aku n colleague front-end aku ada buat for Etherscan, i'll ask him for more info @khrnchn

**Pull request merged**
