### PR TITLE
🗺️ added map and state sorting

### PR DESCRIPTION
**Pull request by Altafxx**
- Added map for render institution 
- Added state filtering
- Partial add institution coordinates
- Added loading state
- Replace X with 𝕏

### CODE REVIEW

**Comment by Altafxx** [comment]
whats the error vercel, tell me sob sob

**Comment by Altafxx** [comment]
> whats the error vercel, tell me sob sob

fix ur pnpm bruv

**Comment by khrnchn** [comment]
@Altafxx on mobile view map tu panjang, other than that perfect

**Comment by Altafxx** [comment]
@khrnchn fixed mate

**Comment by khrnchn** [comment]
bro COOKED cooked

**Pull request merged**
