### PR TITLE
😈 single page

### PR DESCRIPTION
**Pull request by Altafxx**
- Individual page for institution
- Disable motion on clicking card
- Added direct share to whatsapp and X

### CODE REVIEW

**Comment by Altafxx** [comment]
lgtm, ready to merge

**Comment by Altafxx** [comment]
currently using id for slug. will change to name in the future (next few days)

**Comment by Altafxx** [comment]
> sorry was busy tudei, single page ni bila click anywhere on the card eh? btw ada bug
> 
> https://github.com/user-attachments/assets/ac6e83f6-d510-46f7-ae78-7d147c104dd5
> 
> 

Aightt, IT department has been notified

**Comment by Altafxx** [comment]
@khrnchn fixedd

**Comment by khrnchn** [comment]
thanks man! lgtm for now

**Comment by ahmdsye** [comment]
suggestion, instead of clicking anywhere dekat card maybe boleh letak icon mata sebelah dl/share icon utk redirect ke page? sebab macam overlap ngn modal pop up. lagipun takde feedback like kalau web view tunjuk cursor, tapi still prob kat phone view ramai tak tau

**Pull request closed without merging**
