### PR TITLE
add contributor properly

### PR DESCRIPTION
**Pull request by khursani8**
link contributor from issue

~~use id based on issue and plus 1000~~

~~PENDING: separate PR for auto resolving conflict~~

Need to restructure the data, appending will always trigger conflict https://github.com/khrnchn/sedekah-je/pull/255#issuecomment-2466498666

### CODE REVIEW

**Comment by khrnchn** [comment]
nak merge yang ni dulu ke? ke masih wip

**Comment by khursani8** [comment]
dah bole, yg utk conflict tu, mcm kena bincang

sbb data sekarang dkt institution mcm tak standardize lagi, comment tu patut ada proper field sendiri ke atau as comment?
dan comment tu awal2 selepas '{'

yg baru comment selepas '}'

**Comment by khrnchn** [comment]
> dah bole, yg utk conflict tu, mcm kena bincang
> 
> sbb data sekarang dkt institution mcm tak standardize lagi, comment tu patut ada proper field sendiri ke atau as comment? dan comment tu awal2 selepas '{'
> 
> yg baru comment selepas '}'

oh baru perasan hahaha. itulah, plus tak semua masjid ada comment rasanya. haritu masa buat dashboard plan nak add a few fields like contributor (userId), source (masjid/social media), url (link).

**Comment by khursani8** [comment]
> > dah bole, yg utk conflict tu, mcm kena bincang
> > sbb data sekarang dkt institution mcm tak standardize lagi, comment tu patut ada proper field sendiri ke atau as comment? dan comment tu awal2 selepas '{'
> > yg baru comment selepas '}'
> 
> oh baru perasan hahaha. itulah, plus tak semua masjid ada comment rasanya. haritu masa buat dashboard plan nak add a few fields like contributor (userId), source (masjid/social media), url (link). tapi from now onwards letak atas kot dulu, before {

ok2, kalau kau nk try dulu, bole laa
aku kena ada mood dlu hahaha

**Pull request merged**
